name: Data Connect Demo App

on:
  workflow_dispatch:
  pull_request:
    paths:
      - firebase-dataconnect/demo/**
      - .github/workflows/dataconnect_demo_app.yml

defaults:
  run:
    shell: bash
    working-directory: firebase-dataconnect/demo

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  assemble:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: firebase-dataconnect/demo

      - run: echo "13.25.0" >firebase-tools-version.txt

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: firebase-dataconnect/demo/firebase-tools-version.txt

      - run: npm install -g firebase-tools@$(cat firebase-tools-version.txt)

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
          cache-dependency-path: |
            firebase-dataconnect/demo/build.gradle.kts
            firebase-dataconnect/demo/gradle.properties
            firebase-dataconnect/demo/gradle/wrapper/gradle-wrapper.properties

      - name: tool versions
        continue-on-error: true
        run: |
          set +e -xv
          which java
          java -version
          which javac
          javac -version
          which node
          node --version
          which firebase
          firebase --version
          ./gradlew --version

      - run: ./gradlew --no-daemon --info --profile build

      - uses: actions/upload-artifact@v4
        with:
          name: Compiled APKs
          path: firebase-dataconnect/demo/build/**/*.apk
          if-no-files-found: warn
          compression-level: 0

      - uses: actions/upload-artifact@v4
        with:
          name: Gradle Build Reports
          path: firebase-dataconnect/demo/build/reports/
          if-no-files-found: warn
          compression-level: 9

  spotlessCheck:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: firebase-dataconnect/demo

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
          cache-dependency-path: |
            firebase-dataconnect/demo/build.gradle.kts
            firebase-dataconnect/demo/gradle.properties
            firebase-dataconnect/demo/gradle/wrapper/gradle-wrapper.properties

      - name: tool versions
        continue-on-error: true
        run: |
          set +e -xv
          which java
          java -version
          which javac
          javac -version
          ./gradlew --version

      - run: ./gradlew --no-daemon spotlessCheck
